# -*- coding: utf-8 -*-
"""Punto13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NLOShHdXl1NU1r1tT5PzBp6U0Oa9OHCA
"""

import numpy as np
import matplotlib.pyplot as plt
import sympy as sym

def GetLegendre(n):
    
    x = sym.Symbol('x',Real=True)
    y = sym.Symbol('y',Real=True)
    
    y = (x**2 - 1)**n
    
    p = sym.diff(y,x,n)/(2**n * np.math.factorial(n))
    
    return p

#De despejar del mismo polinomio x^2:
x2 = ((2/3) * GetLegendre(2)) + ((1/3) * GetLegendre(0))
x1 = GetLegendre(1)
x0 = GetLegendre(0)
#Entonces quedaría: 

a =(3*x0) + (5*x1) + (1*((2/3)*x2 + (1/3)*x0))
print("En términos de polinomios de Legrenge, se puede escribir p(x) como:" , a)
print("Se debe tener en cuenta que la respuesta queda en forma de decimales y no fraccionarios.")